Repository cosmos/iavl, pull requests merged in 2020-06, with the labels that each got.

#254 add codecov
  .github/workflows/ci.yml
  codecov.yml
Labels: S:automerge

#255 add codecov tags & center
  .github/workflows/lint.yml
  README.md
Labels: S:automerge

#251 Version Metadata
  docs/architecture/adr-001-flush-version.md
  go.mod
  go.sum
  metadata.go
  metadata_test.go
  mutable_tree.go
  nodedb.go
  nodedb_test.go
  pruning_test.go
  types.pb.go
  types.proto
Labels: T:enhancement

#239 FlushVersion API
  CHANGELOG.md
  mutable_tree.go
  mutable_tree_test.go
  nodedb.go
Labels: P:High, T:enhancement

#262 document byte slice immutability
  immutable_tree.go
  mutable_tree.go
Labels: S:automerge

#263 test: fix byte slice reuse
  export_test.go
Labels: S:automerge

#267 add test case for pruning tail
  pruning_test.go
Labels: S:automerge

#269 test: fix random failure in TestVersionedTreeProofs
  testutils_test.go
  tree_test.go
Labels: S:automerge

#271 DeleteVersions
  go.mod
  go.sum
  mutable_tree.go
  mutable_tree_test.go
Labels: S:wip, T:enhancement

#272 test: add randomized tests
  tree_random_test.go
Labels: S:automerge

#275 fix LoadVersionForOverwriting data corruption
  mutable_tree.go
  nodedb.go
  tree_random_test.go
  tree_test.go
Labels: T:bug

#277 update changelog
  CHANGELOG.md
Labels: S:automerge

#279 bump tm-db
  benchmarks/bench_test.go
  benchmarks/cosmos-exim/main.go
  cmd/iaviewer/main.go
  go.mod
  go.sum
  import.go
  mutable_tree_test.go
  nodedb.go
  testutils_test.go
Labels: S:automerge, T:dependencies

#285 update module path to github.com/cosmos/iavl
  CHANGELOG.md
  Makefile
  README.md
  benchmarks/README.md
  benchmarks/bench_test.go
  benchmarks/cosmos-exim/main.go
  benchmarks/hash_test.go
  benchmarks/setup/RUN_BENCHMARKS.sh
  cmd/iaviewer/README.md
  cmd/iaviewer/main.go
  doc.go
  docs/proof/proof.md
  go.mod
  proof.go
  proof_test.go
  testutils_test.go
  tree_fuzz_test.go
  tree_test.go
Labels: T:breaking

#265 remove Amino
  docs/node/node.md
  encoding.go
  export_test.go
  node.go
  node_test.go
  nodedb.go
  proof.go
  testutils_test.go
  tree_test.go
Labels: S:automerge
