Repository cosmos/iavl, pull requests merged in 2020-05, with the labels that each got.

#244 README: add GoDoc badge
  README.md
Labels: C:docs, S:automerge

#245 doc: specify concurrency characteristics
  doc.go
  immutable_tree.go
  mutable_tree.go
Labels: C:docs, S:automerge

#249 ci: bump linting
  .github/workflows/lint.yml
  cmd/iaviewer/main.go
  mutable_tree_test.go
  nodedb.go
Labels: S:automerge

#250 ADR 001 - Flush Version
  docs/architecture/README.md
  docs/architecture/adr-001-flush-version.md
  docs/architecture/adr-template.md
Labels: C:docs
