Repository cosmos/iavl, pull requests merged in 2022-08, with the labels that each got.

#527 make: don't run tests on benchmark
  Makefile
Labels: T:enhancement, S:automerge

#525 perf: use fast unsafe bytes->string convertion
  CHANGELOG.md
  cache/cache.go
  cmd/iaviewer/main.go
  internal/bytes/bytes.go
  internal/bytes/string.go
  internal/bytes/string_test.go
  mutable_tree.go
  nodedb.go
  tree_dotgraph.go
  unsafe.go
  unsaved_fast_iterator.go
Labels: T:performance

#540 golangci-lint configuration
  .golangci.yml
Labels: S:automerge

#536 linting fixes
  benchmarks/cosmos-exim/main.go
  cache/cache.go
  doc.go
  fast_node.go
  immutable_tree.go
  iterator.go
  key_format.go
  node.go
  nodedb.go
  proof.go
  proof_range.go
Labels: S:automerge
